### ISSUE TITLE
Allow Channel Values to be changed on their pages

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-slsc-eds-custom-device#18]
This issue was migrated from https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues/8

Right now you can only change the channel value in the main page.

**Comment by Alexbarp** [comment]
Hey @Austrim and @Karl-G1 , I am tagging you so you can "manage" this request. I believe this was already fixed in another submission. Could you verify this and mark this request as Closed before this gets incorporated into DevOps. Thanks.

**Comment by Karl-G1** [comment]
Confirmed this feature was added in #15
