### ISSUE TITLE
Need ability to change the Custom Device Name

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-slsc-eds-custom-device#20]
This issue was migrated from https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues/6

This would help differentiate between different boards using the EDS.

**Comment by Alexbarp** [comment]
Hey @Austrim and @Karl-G1 , I am tagging you so you can "manage" this request. I believe this was already fixed in another submission. This is possible in VS 2017 and later. Just wanted to clean up this request (and marked as Closed) before this gets incorporated into DevOps.

**Comment by Karl-G1** [comment]
Confirmed this feature was added in https://github.com/ni/niveristand-slsc-eds-custom-device/pull/15
