### ISSUE TITLE
Multi-Property Value Application

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-slsc-eds-custom-device#21]
This issue was migrated from https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues/5

I'd love to see the ability to change properties that share the same datatype simultaneously, i.e. select all the relevant switches using Shift and set the value appropriately to be reflected across all of them.

**Comment by Alexbarp** [comment]
I think I implemented this feature in the latest version of the EDS. You can use "shift" and select several elements of the same type and change its value. Before it used to not allow that. Could you confirm that this is behaving as Lynn would expect, @rtzoeller, @csjall ?

**Comment by Alexbarp** [comment]
Hey @Austrim and @Karl-G1 , I am tagging you so you can "manage" this request. I believe this was already fixed. Just wanted to clean up house before this gets incorporated into DevOps with no need.

**Comment by Karl-G1** [comment]
Confirmed this feature was added in #15
