### ISSUE TITLE
Import/Export Capability Needed

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-slsc-eds-custom-device#22]
This issue was migrated from https://github.com/NIVeriStandAdd-Ons/SLSC-EDS-Plugin-Custom-Device/issues/4

It would be ideal to have import/export capability for the individual custom device. This will allow me to export/import common configurations of modules and minimize channel bloat.

**Comment by Alexbarp** [comment]
I believe that this feature was already implemented. You can easily get a capability from one CD EDS to another with the "import" and "export" buttons. Should we close this @rtzoeller, @csjall ?

**Comment by Alexbarp** [comment]
Hey @Austrim and @Karl-G1 , I am tagging you so you can "manage" this request. I believe this was already fixed. Just wanted to clean up house before this gets incorporated into DevOps with no need.

**Comment by Karl-G1** [comment]
Confirmed this feature was added in https://github.com/ni/niveristand-slsc-eds-custom-device/pull/15
