### ISSUE TITLE
Command Default Value Reverts Back to Previous Data After I Save

### ISSUE THREAD

**Issue by Alexbarp** [ni/niveristand-slsc-eds-custom-device#34]
I was working with the SLSC-12252 and I was trying to make the Command "FaultUpdate" to be used as "[2] Apply on Change". However, after I do that and I try to "save", the value reverts back to "[0] No change". I also noticed that properties do not work either.
If you change and "export" that configuration, then the values are reverted to that configuration, which was [2] after I changed. 
It looks like the "save" is not synchronizing with the exact value and it is reverted... and this is a major problem since it makes the EDS very hard to use (since you have to keep exporting to stick the value).\
Please see this issue, @Karl-G1 @Austrim since that seemed pretty bad... (and the fix should be simple).

**Comment by Karl-G1** [comment]
I did some regression testing in VeriStand 2019, and this was working in ebd12818d6e4135324eec44dcb99c1522ebf37ce and broke in c844202723751d834255f893179a30e1eca8a018. So it appears that PR https://github.com/ni/niveristand-slsc-eds-custom-device/pull/15 introduced this issue. I will add this and https://github.com/ni/niveristand-slsc-eds-custom-device/issues/35 to our working backlog.

**Comment by Alexbarp** [comment]
Just FYI, it looks like I can "click" using VS 2017, which was the version that I tested those changes. So, please verify if this could influence the changes. Also, noticed that I worked with Cerna about creating a Manual test for this Custom Device. This should capture those problems.

**Comment by Karl-G1** [comment]
@Alexbarp It looks like this issue (saving default values) reproduces across VS 2017-2019. The mouse down issue (https://github.com/ni/niveristand-slsc-eds-custom-device/issues/35) only reproduces in VS 2018 and later.

**Comment by buckd** [comment]
> Just FYI, it looks like I can "click" using VS 2017, which was the version that I tested those changes. 

@Alexbarp  I just tested in 2017, and it does not always work. Sometimes it does, and sometimes it doesn't. On my machine, most of the time it doesn't work. On @Karl-G1's test machine, it works most of the time.
