### ISSUE TITLE
unable to select items in tree

### ISSUE THREAD

**Issue by smithed180** [ni/niveristand-slsc-eds-custom-device#35]
you have to select the tree and then use arrow keys to navigate. Just clicking on a tree item does not select it. It appears to somehow select the columns, but not rows. This is just after a mousedown on the [2]Apply on change section of the tree:
![image](https://user-images.githubusercontent.com/53264791/72285659-9461c200-3611-11ea-96fd-95fef904e65c.png)

**Comment by Karl-G1** [comment]
I did some regression testing in VeriStand 2019, and this was working in ebd12818d6e4135324eec44dcb99c1522ebf37ce and broke in c844202723751d834255f893179a30e1eca8a018. So it appears that PR https://github.com/ni/niveristand-slsc-eds-custom-device/pull/15 introduced this issue. I will add this and https://github.com/ni/niveristand-slsc-eds-custom-device/issues/34 to our working backlog.

**Comment by Karl-G1** [comment]
It looks like this comment (https://github.com/ni/niveristand-slsc-eds-custom-device/issues/34#issuecomment-573876607) belongs on this issue.

I tested across versions and builds, and it looks like VeriStand 2017 does not have this problem. 2018 and 2019 do have the problem.

**Comment by buckd** [comment]
I've reproduced this in 2017 as well. On my test machine, it fails to highlight items most times, but every once in a while it works.
