### ISSUE TITLE
Remove all 2015/2016 conditional code

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-slsc-eds-custom-device#38]
There are lots of conditional disable structures in the custom device that handle code paths for 2015/2016 that are obsolete now that the custom device will no longer support those versions. All of that conditional code, the symbol in the project, and the codegen steps in `build.toml` should be removed.

**Comment by Alexbarp** [comment]
Also, remove the "Custom Device ***.xml" file from the project since this is only used for previous versions too.

**Comment by Alexbarp** [comment]
And if this happens for 2017 and later, I strongly encourage you to use this tool for converting JSON files into data structures: https://github.com/ni/slsc-capability-explorer that is only supported after 2017.

**Comment by rtzoeller** [comment]
Disclaimer: I am not a lawyer and this should not be considered legal guidance.

We should consider the licensing implications of using that repository (whic is GPL v3 licensed) in the custom device. While as the copyright holders I believe we can use it in EDS (which is MIT licensed) without an issue, doing so today would force customers and integrators who want to modify it to release their modifications under the GPL license, which is likely unacceptable.

"The GNU General Public License does not permit incorporating your program
into proprietary programs."

**Comment by Alexbarp** [comment]
I would advise to look again to the license used for this repository and really verify if it has the right license there. I am not sure if there was a proper review for the option used by that repository.

**Comment by Karl-G1** [comment]
Fixed by #52
