### ISSUE TITLE
Build 21.0.0.8 have incomplete engine libraries for Linux32 and Pharlap

### ISSUE THREAD

**Issue by brunocesy** [ni/niveristand-slsc-eds-custom-device#65]
I tried this build >> ni-slsc-eds-veristand-2020-support_21.0.0.8_windows_x64.nipkg
and noticed it comes with empty Pharlap and Linux32 engine libraries at
C:\Users\Public\Documents\National Instruments\NI VeriStand 2020\SLSC Plugins\Modules\SLSC EDS
VeriStand complains giving warning dialogs for each SLSC card every time opening a project which contains EDS on the sysdef, even the project is for a Linux64 target.
The workaround I am doing right now is using the previous build >> ni-slsc-eds-veristand-2020-support_20.5.0.2_windows_x64.nipkg
This one comes with all good libraries. Hope maintainers can please mind for a fix.
Thanks.

**Comment by rtzoeller** [comment]
@brunocesy VeriStand 2021 removed support for PharLap or Linux ARM targets, which led us to drop support for PharLap and Linux ARM targets from the 21.0 custom devices as well (see the [custom device release notes](https://github.com/ni/niveristand-slsc-eds-custom-device/releases/tag/v21.0.0)).

As you noticed, we [still generate](https://github.com/ni/niveristand-slsc-eds-custom-device/commit/7383af2c9339d902bc30c69c89e6a18bc9422d8e) LLBs for the PharLap and Linux ARM targets, although they are empty. This should prevent any warnings from occurring when loading the system definition.

If you can provide a system definition which reproduces the behavior you're describing, I'm happy to look into why the warnings dialogs are appearing. Although we don't support PharLap and Linux ARM targets, a warning should not be appearing.

**Comment by brunocesy** [comment]
Thanks Ryan for the info. Unfortunately it was a big move to change versions on development PC, RT System Image, etc.. I cannot revert to that state easily now. But it is fine, maybe is better to stick with EDS 20.x in my case.
